name: CI
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pertemuan-09-cicd/pbl-taskflow-go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Fix go.mod dan generate go.sum
        run: |
          sed -i 's|github.com/jackc/pgservicefile v0.0.0-20231201235250-de7065d787f4|github.com/jackc/pgservicefile v0.0.0-20200307190119-3fe961f6962c|g' go.mod
          go mod tidy
      - name: Run unit tests
        run: go test ./internal/validator/... ./internal/service/... ./internal/repository/... -v -timeout 30s
